### ISSUE TITLE
Incorrect escaping of `\` in tail position

### ISSUE THREAD

**Issue by Suavesito-Olimpiada** [JuliaStrings/LaTeXStrings.jl#66]
The MWE is the following

```.julia
julia> L"\\" # expected "\$\\\\\$"
L"$\$"

julia> L"$\\$" # works as expected
L"$\\$"

julia> L"$\\" # also works as expected
L"$\\"

julia> L"\\" # "eats" the last backslash
L"$\$"

julia> L"\\\\" # expected "\$\\\\\\\\\$" = L""
L"$\\$"

julia> println(L"\\$") # works as expected
$\\$$
```

(I guess this is simply a symptom of [Julia escaping rules for strings](https://github.com/JuliaLang/julia/issues/39092).)

**Comment by stevengj** [comment]
Yes, backslashes before the final quote mark must be escaped in Julia custom string-literal syntax.  See https://docs.julialang.org/en/v1/manual/strings/#man-raw-string-literals

Nothing we can do about it in individual packages.

**Comment by vtjnash** [comment]
Individual packages can call `escape_raw_string` (as noted in that link) at the start of the macro, if they meet the conditions  that (a) users do not call them with `@L_str "normal string"` syntax (b) a trailing `\` has no useful meaning (it is an error) (c) the sequence `\"` would be interpreted as a plain " (d) the escape character is `\`. For example, `macro b_str` meets these restrictions, so a valid improvement to that implementation would have been to call `unescape_string(escape_raw_string(str)))` to reverse the raw-string transform then apply the unescape_string transform which is a superset of it (unfortunately for `b_str` itself, doing so now might be considered a breaking change)
