### ISSUE TITLE
release version 1.3.1?

### ISSUE THREAD

**Issue by lmiq** [JuliaStrings/LaTeXStrings.jl#68]
It seems that version 1.3.1 was not released (and that fixes method ambiguities that are causing Aqua tests to fail in other packages, apparently).

**Comment by stevengj** [comment]
Whoops, thanks for noticing this.  I tried registering in https://github.com/JuliaStrings/LaTeXStrings.jl/commit/6a93912e4ea27469b1d29932fb455fa14f32f160#commitcomment-131386831 but https://github.com/JuliaRegistries/General/pull/94515 needs to be merged first.

**Comment by stevengj** [comment]
Will be closed by https://github.com/JuliaRegistries/General/pull/94573
