### ISSUE TITLE
How to underline a text in julia using Latex String?

### ISSUE THREAD

**Issue by sivabkumar** [JuliaStrings/LaTeXStrings.jl#71]
using Plots

using LaTeXStrings
x = [1,2,3,4,5]
y = x .^2
plot(x,y,label = L"\underline{x}")

This code will give an error

but instead of \underline if I am using \overline work.

That is 

plot(x,y,label = L"\overline{x}")

But I need \underline. 

Please solve my problem.

Thanks in advance

**Comment by stevengj** [comment]
There is nothing that LaTeXStrings can do about this — it doesn't do any rendering, it just sends the `\underline{x}` to the `plot` backend.  So your are limited by whatever math formatting is supported by the math display of your plot backend.

If you are using the PyPlot/Matplotlib backend, see [this stackoverflow question](https://stackoverflow.com/questions/46009701/matplotlib-text-underline) and https://github.com/matplotlib/matplotlib/issues/14235

If you are using Makie, then it uses https://github.com/Kolaru/MathTeXEngine.jl to render latex equations, see https://github.com/Kolaru/MathTeXEngine.jl/issues/121
