### ISSUE TITLE
Hyphens are turned into minus signs

### ISSUE THREAD

**Issue by vpuri3** [JuliaStrings/LaTeXStrings.jl#73]
```julia
julia> using CairoMakie, LaTeXStrings;

julia> f = Figure(; size = (200, 50));

julia> Label(f[1,1], L"This is a hyphen (-)\\ That is a minus sign $(-)$. That is an en-dash (--)")

julia> f
```

![image](https://github.com/JuliaStrings/LaTeXStrings.jl/assets/36345239/375231f0-a4af-4877-8558-f0011b3fb356)

Is it possible to work around this issue?

**Comment by stevengj** [comment]
See the FAQ: https://github.com/JuliaStrings/LaTeXStrings.jl?tab=readme-ov-file#faq-not-a-latex-renderer

LaTeXStrings has nothing to do with this.

**Comment by vpuri3** [comment]
Thanks for clarifying. I'll move this over to Makie.jl.
